[workspace]
members = [
    "alacritty",
    "alacritty_terminal",
    "alacritty_config",
    "alacritty_config_derive",
]

[patch.crates-io]
calloop = { git = "https://github.com/Smithay/calloop" }

[profile.release]
lto = true
debug = 1
incremental = false
